version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5002:5002"
    # choose ONE of these blocks:

    # (A) If you use dotenv inside the container (see backend Dockerfile & code):
    volumes:
      - ./backend/.env:/app/.env:ro

    # (B) If you prefer compose-injected env (no dotenv in code), use this instead of the volume above:
    # env_file:
    #   - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    # Expose API URL to Vite dev server (browser will call public host/IP)
    environment:
      - VITE_API_URL=http://212.85.26.216:5002/api
    # (optional for hot-reload)
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
