import api from "./axios";
export const getDeliveredDaily   = (params) => api.get("/analytics/delivered/daily",   { params }).then(r => r.data.data);
export const getDeliveredMonthly = (params) => api.get("/analytics/delivered/monthly", { params }).then(r => r.data.data);
export const getStatusDaily      = (params) => api.get("/analytics/status/daily",      { params }).then(r => r.data.data);
export const getTopCities        = (params) => api.get("/analytics/top-cities",        { params }).then(r => r.data.data);
export const getTopCategories    = (params) => api.get("/analytics/top-categories",    { params }).then(r => r.data.data);
export const getSLA             = (params) => api.get("/analytics/sla",               { params }).then(r => r.data.data);
export const getFunnel          = (params) => api.get("/analytics/funnel",            { params }).then(r => r.data.data);
export const getRevenueMonthly  = (params) => api.get("/analytics/revenue/monthly",   { params }).then(r => r.data.data);
export const getPaymentsMix     = (params) => api.get("/analytics/payments/mix",      { params }).then(r => r.data.data);
export const getReviewsSummary  = (params) => api.get("/analytics/reviews/summary",   { params }).then(r => r.data.data);
export const getBasketSize      = (params) => api.get("/analytics/basket/size",       { params }).then(r => r.data.data);
export const getFreightScatter  = (params) => api.get("/analytics/freight/scatter",   { params }).then(r => r.data.data);
export const getLeadtimeBreak   = (params) => api.get("/analytics/leadtime/breakdown",{ params }).then(r => r.data.data);
export const getPurchaseHeatmap = (params) => api.get("/analytics/purchase/heatmap",  { params }).then(r => r.data.data);
export const getSellersPareto   = (params) => api.get("/analytics/sellers/pareto",    { params }).then(r => r.data.data);
